typography_spectrum: 0.9700377881526947
color:
  brandStrength: 0.705133989918977
  lightness: 0.6508143737446517
  saturation: 0.16510000941343606
  rhythmicContrast: 0.65870117302984
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
layout_spectrum: 0.1195686908904463
name: Aurizn
title: Aurizn
description: Horizon
